#ifndef COMPILER_HH_INCLUDED_20181221
#define COMPILER_HH_INCLUDED_20181221

#define PUFFIN_HAS_CONSTEXPR      false
#define PUFFIN_HAS_ALIAS_TEMPLATE false
#define PUFFIN_HAS_MOVE_SEMANTICS false

#define PUFFIN_CONSTEXPR
#define PUFFIN_NOEXCEPT

#endif // COMPILER_HH_INCLUDED_20181221
